import PinterestGrid from "@/components/PinterestGrid";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: 'Inspiration ',
  description: 'Get inspired by the latest images generated by Imagen Fly.',
}

export default function InspirationScreen() {
  return (
    <div className="flex flex-col items-center justify-center h-full space-y-4 w-full">
      <PinterestGrid imageUrls={[]} />
    </div>
  )
}
